# Generated by Django 2.0.4 on 2018-05-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paw_blog', '0002_auto_20180502_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
